### ISSUE TITLE
__getitem__ demands a Python long integer

### ISSUE THREAD

**Issue by jacobbond** [eudoxos/minieigen#14]
When trying to get an item out of a VectorXmp, `__getitem__` demands a Python long integer.  It doesn't actually affect functionality and it can be worked around in code with `long(str(index))`.

```
sage: y_end[1]
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-53-4e4a51777556> in <module>()
----> 1 y_end[Integer(1)]

ArgumentError: Python argument types in
    VectorXmp.__getitem__(VectorXmp, Integer)
did not match C++ signature:
    __getitem__(Eigen::Matrix<bertini::complex, -1, 1, 0, -1, 1>, long)
sage: y_end[1L]
(0.0000000000000000e+00, 0.0000000000000000e+00)
```

The same behavior occurs with `VectorXd`.  I found that Python's `int`s are implemented using `long`s ([here](https://docs.python.org/2/library/stdtypes.html#numeric-types-int-float-long-complex)), so there is kind of a disconnect between what Python might pass as an `int` and what C++ can accept as an `int`.

**Comment by ofloveandhate** [comment]
i note that `VectorMp` is from [Bertini2](github.com/bertiniteam/b2), where we use minieigen as a dependency for our Python bindings.  In the plain old minieigen case, the type is probably `Vecd`?  I'd have to go back and read the code.

**Comment by eudoxos** [comment]
I commented in https://github.com/bertiniteam/b2/issues/49, it is out of scope of minieigen (the arg you pass is sage's `Integer`, not Python's `builtins.int`).
