### ISSUE TITLE
unable to compile and install with opensuse15.0

### ISSUE THREAD

**Issue by Oger35** [eudoxos/minieigen#17]
the new operating system Opensuse leap 15.0 uses some news boost library (1.66) coupled with python 3.6. this new configuration makes the python setup.py install not able to compile all  the cpp file
How to update the setup.py file?

**Comment by eudoxos** [comment]
Hi Oger35, what is the error you are seeing? Please paste here, it will be valuable. Is it a problem in boost::python? Here with 1.65 everything is okay, maybe changelog for 1.66 will contain something interesting. Best, Vaclav

**Comment by Oger35** [comment]
Dear Sir,

during the compilation of the second  file I got a huge list of error and warning lines

so here the log file
[minieigen_log.txt](https://github.com/eudoxos/minieigen/files/2143025/minieigen_log.txt)

**Comment by eudoxos** [comment]
The first error is about `boost::is_complex` here: https://github.com/eudoxos/minieigen/blob/7bd0a2e823333477a2172b428a3801d9cae0800f/src/visitors.hpp#L107 but in the current version there is `Eigen::NumTraits<Scalar>::IsComplex`, not `boost::is_complex` - it used to be there a few years back. Make sure you update first from the repo, the error should be gone then. Please confirm.

**Comment by Oger35** [comment]
I have downloaded the latest release available in https://pypi.org/project/minieigen/ which is 0.5.3
your link is pointing to a different version. Right now, the gcc compilation went correct but bothpython 2.7 and 3.6 does not generate the library at the end, both have this error:

_creating build/lib.linux-x86_64-2.7
g++ -pthread -shared build/temp.linux-x86_64-2.7/src/minieigen.o build/temp.linux-x86_64-2.7/src/expose-boxes.o build/temp.linux-x86_64-2.7/src/expose-complex.o build/temp.linux-x86_64-2.7/
src/expose-converters.o build/temp.linux-x86_64-2.7/src/expose-matrices.o build/temp.linux-x86_64-2.7/src/expose-quaternion.o build/temp.linux-x86_64-2.7/src/expose-vectors.o build/temp.lin
ux-x86_64-2.7/src/double-conversion/bignum.o build/temp.linux-x86_64-2.7/src/double-conversion/bignum-dtoa.o build/temp.linux-x86_64-2.7/src/double-conversion/cached-powers.o build/temp.lin
ux-x86_64-2.7/src/double-conversion/diy-fp.o build/temp.linux-x86_64-2.7/src/double-conversion/double-conversion.o build/temp.linux-x86_64-2.7/src/double-conversion/fast-dtoa.o build/temp.l
inux-x86_64-2.7/src/double-conversion/fixed-dtoa.o build/temp.linux-x86_64-2.7/src/double-conversion/strtod.o -L/usr/lib64 -lboost_python-py27 -lpython2.7 -o build/lib.linux-x86_64-2.7/mini
eigen.so
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld : ne peut trouver -lboost_python-py27
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1_

or the same with   -lboost_python-py36 for python3

in my OS Opensuse leap 15.0, the library are only boost_python.so or boost_python3.so linked to  boost_python-py2_7 or py3  see 
lrwxrwxrwx 1 root root     22 12 mai   10:55 libboost_python3.so -> libboost_python-py3.so
lrwxrwxrwx 1 root root     31 12 mai   10:55 libboost_python-py2_7.so -> libboost_python-py2_7.so.1.66.0
-rwxr-xr-x 1 root root 833168 12 mai   10:55 libboost_python-py2_7.so.1.66.0
lrwxrwxrwx 1 root root     29 12 mai   10:54 libboost_python-py3.so -> libboost_python-py3.so.1.66.0
-rwxr-xr-x 1 root root 820584 12 mai   10:55 libboost_python-py3.so.1.66.0
lrwxrwxrwx 1 root root     24 12 mai   10:55 libboost_python.so -> libboost_python-py2_7.so

So I had to make links to have py27 and py36 as part of the name and by this way I was able to finish the setup.py install
thanks

**Comment by eudoxos** [comment]
Don't use pypi, it is not the latest code. Use `pip3 install git+https://github.com/eudoxos/minieigen.git` to use latest git transparently.

**Comment by Oger35** [comment]
I have used pip3 but finally I got the same error about the link to the boost_python library which, by default does not have the right "_pyversionnumber" part of the name:

"   /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld : ne peut trouver -lboost_python-py34
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1"

**Comment by MaxWiebicke** [comment]
I had the same problem, because I forgot to install the boost packages. It was working for me after installing them (on Xubuntu 18.04)
`sudo apt-get install libboost-all-dev`

**Comment by donttouchthis** [comment]
@Oger35 I get the same error or Fedora 29 (and 27). 
The current master branch is working after some modifications to the  `setup.py` (0.5.3 is working with the same fix till Fedora 27)

```python
import platform
if platform.linux_distribution()[0] == 'Fedora':
    libraries=['boost_python' if sys.version_info[0] == 2 else 'boost_python3']
else:
    libraries=['boost_python-py%d%d'%(sys.version_info[0],sys.version_info[1])]
```

**Comment by eudoxos** [comment]
@donttouchthis please create a PR for your change, I will incorporate it. Thanks
