### ISSUE TITLE
Cant install 'minieigen'

### ISSUE THREAD

**Issue by sagively** [eudoxos/minieigen#20]
Hello,

I'm trying to install minieigen but with no success.
For that reason I can't use your evaluation and training code.

The error I get is:
"Eigen/Core: No such file or directory" (more details in the figure)

![figure1](https://user-images.githubusercontent.com/49648225/56491684-06c5cb80-64f2-11e9-97dc-0c56bd0f8168.JPG)

If you have any ideas how can I solve it, it would be great!

Thanks!

**Comment by eudoxos** [comment]
You need to install Eigen headers, usually package like libeigen3-dev or libeigen3-devel or such. This is not an issue of minieigen.
