### ISSUE TITLE
Could you release a tutorial for beginners?

### ISSUE THREAD

**Issue by Photonico** [eudoxos/minieigen#21]
I have never used C++ and Eigen. I want to use this package for my scientific computation.
Will you release some tutorials for beginners?
I think it will benefit you to develop this package.

Sincerely,
Lu

**Comment by eudoxos** [comment]
Hi, if you work in c++, use Eigen, which has extensive documentation. If you work in Python, use numpy, which also has extensive documentation. If you need to bridge those, use Eigen in c++, numpy in Python and interface them using pybind11, which likewise has extensive documentation.

minieigen is interesting only for historical projects which still use boost::python, and there are no plans to develop it further.

Good luck!
