### ISSUE TITLE
Debian packaging for Python3

### ISSUE THREAD

**Issue by eudoxos** [eudoxos/minieigen#6]
Minieigen has python3 packaging included in its debian scripts (http://bazaar.launchpad.net/~eudoxos/minieigen/minieigen-debian/view/head:/control), is there something else I should do? Cheers, v.

**Comment by gladk** [comment]
It looks fine. Could you please also tag a release? In Debian we have an "artificial" number 0.41 currently.

Thanks

**Comment by eudoxos** [comment]
Thanks. I tagged it 0.4-2 (so that it is consistent with the version in setup.py), but I can change it to 0.42, no problem. Does this number have to be a valid debian number? It gets used automatically instead of the number in `debian/changelog`?

**Comment by gladk** [comment]
0.42 would be much better, or 0.5 is also OK.

Prefix with -X you should add only in d/changelog/:
UpstreamVersion-X

**Comment by eudoxos** [comment]
I bumped the version to 0.5 and tagged it as such. Let me know if something is still not ok.
