### ISSUE TITLE
Installation of version 0.5 is broken with pip

### ISSUE THREAD

**Issue by mboisson** [eudoxos/minieigen#8]
There are missing headers when you do a "pip install minieigen". Version 0.4 worked fine.

**Comment by eudoxos** [comment]
Thanks for reporting. Could you perhaps paste terminal output so that the error is visible? I am not aware of any change of headers between 0.4 and 0.5; last big changes were splitting the source into separate source files to save RAM when compiling (f652b3003df7a1eec7dbb5f4a4356801d3e07227) and adding complex support (5a44a15eab995f1e2eef0c289b83e6e9e8b7b9ed). Could you possibly branch this repo and run `python setup.py install` to try locally so that we see if it is git issue or pypi issue?

**Comment by mboisson** [comment]
Sure. Here is the output : 

```
(myvenv)[mboisson@colosse2 tmp]$ pip install minieigen
Downloading/unpacking minieigen
  Downloading minieigen-0.5.tar.gz (41kB): 41kB downloaded
  Running setup.py (path:/home/mboisson/tmp/myvenv/build/minieigen/setup.py) egg_info for package minieigen

Installing collected packages: minieigen
  Running setup.py install for minieigen
    building 'minieigen' extension
    /software6/compilers/gcc/4.8/bin/gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DEIGEN_DONT_ALIGN -Isrc -I/usr/include/eigen3 -Iminieigen -I/software6/apps/python/2.7.5/include/python2.7 -c src/minieigen.cpp -o build/temp.linux-x86_64-2.7/src/minieigen.o
    cc1plus: attention : command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    src/minieigen.cpp:14:21: erreur fatale: common.hpp : Aucun fichier ou dossier de ce type
     #include"common.hpp"
                         ^
    compilation terminée.
    error: command '/software6/compilers/gcc/4.8/bin/gcc' failed with exit status 1
    Complete output from command /home/mboisson/tmp/myvenv/bin/python -c "import setuptools, tokenize;__file__='/home/mboisson/tmp/myvenv/build/minieigen/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WWBxBI-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/mboisson/tmp/myvenv/include/site/python2.7:
    running install

running build

running build_ext

building 'minieigen' extension

creating build

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

creating build/temp.linux-x86_64-2.7/src/double-conversion

/software6/compilers/gcc/4.8/bin/gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DEIGEN_DONT_ALIGN -Isrc -I/usr/include/eigen3 -Iminieigen -I/software6/apps/python/2.7.5/include/python2.7 -c src/minieigen.cpp -o build/temp.linux-x86_64-2.7/src/minieigen.o

cc1plus: attention : command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

src/minieigen.cpp:14:21: erreur fatale: common.hpp : Aucun fichier ou dossier de ce type

 #include"common.hpp"

                     ^

compilation terminée.

error: command '/software6/compilers/gcc/4.8/bin/gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /home/mboisson/tmp/myvenv/bin/python -c "import setuptools, tokenize;__file__='/home/mboisson/tmp/myvenv/build/minieigen/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WWBxBI-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/mboisson/tmp/myvenv/include/site/python2.7 failed with error code 1 in /home/mboisson/tmp/myvenv/build/minieigen
Traceback (most recent call last):
  File "/home/mboisson/tmp/myvenv/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/mboisson/tmp/myvenv/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/home/mboisson/tmp/myvenv/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 45: ordinal not in range(128)
```

**Comment by mboisson** [comment]
It works fine if I do the following instead of using pip : 

```
wget -O minieigen-0.5.zip https://github.com/eudoxos/minieigen/archive/0.5.zip
unzip minieigen-0.5.zip && cd minieigen-0.5
python setup install
```

**Comment by mboisson** [comment]
Note that there are no header files in the package downloaded by pip : 

```
(myvenv)[mboisson@colosse2 tmp]$ tar xfvz https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fm%2Fminieigen%2Fminieigen-0.5.tar.gz
minieigen-0.5/
minieigen-0.5/src/
minieigen-0.5/src/expose-matrices.cpp
minieigen-0.5/src/minieigen.cpp
minieigen-0.5/src/double-conversion/
minieigen-0.5/src/double-conversion/strtod.cc
minieigen-0.5/src/double-conversion/cached-powers.cc
minieigen-0.5/src/double-conversion/double-conversion.cc
minieigen-0.5/src/double-conversion/bignum-dtoa.cc
minieigen-0.5/src/double-conversion/fixed-dtoa.cc
minieigen-0.5/src/double-conversion/bignum.cc
minieigen-0.5/src/double-conversion/fast-dtoa.cc
minieigen-0.5/src/double-conversion/diy-fp.cc
minieigen-0.5/src/expose-vectors.cpp
minieigen-0.5/src/expose-converters.cpp
minieigen-0.5/src/expose-quaternion.cpp
minieigen-0.5/src/expose-boxes.cpp
minieigen-0.5/src/expose-complex.cpp
minieigen-0.5/README.txt
minieigen-0.5/PKG-INFO
minieigen-0.5/setup.py
```

**Comment by eudoxos** [comment]
Well spotted, thanks. As quick workaround, install the last working version with `pip install minieigen==0.4-1` and I will look at why is the header not uploaded and report here in short.

**Comment by eudoxos** [comment]
Hmm, still not ok.

**Comment by eudoxos** [comment]
0.5.2 in pypi is OK for building via pip now. If you still have issues, reopen or open a new issue. Thanks for report.

**Comment by mboisson** [comment]
It is currently building. Not done yet, but I do not have the missing header error anymore, so it's looking good.

**Comment by Kimeu-Jeff** [comment]
can someone help me. am trying to install miniegen using pip and have installed MS VS Build tools but am getting this error
-----------------------------------
PS C:\Users\kimeu> pip install minieigen
Collecting minieigen
  Using cached https://files.pythonhosted.org/packages/3b/3b/04201858d7f0dc8dffad00b48207edffbf2ae63196f4b7b8f67b2a00578d/minieigen-0.5.4.tar.gz
Building wheels for collected packages: minieigen
  Building wheel for minieigen (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\kimeu\.virtualenvs\demon_venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kimeu\\AppData\\Local\\Temp\\pip-install-nw28wq3y\\minieigen\\setup.py'"'"'; __file__='"'"'C:\\Users\\kimeu\\AppData\\Local\\Temp\\pip-install-nw28wq3y\\minieigen\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\kimeu\AppData\Local\Temp\pip-wheel-zq0l6r38' --python-tag cp37
       cwd: C:\Users\kimeu\AppData\Local\Temp\pip-install-nw28wq3y\minieigen\
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'minieigen' extension
  creating build
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\src
  creating build\temp.win-amd64-3.7\Release\src\double-conversion
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -DEIGEN_DONT_ALIGN -DEIGEN_DONT_VECTORIZE -Isrc -Ic:\src\boost_1_51_0 -Ic:\src\eigen-3.1.1 "-Ic:\program files\python37\include" "-Ic:\program files\python37\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpsrc/minieigen.cpp /Fobuild\temp.win-amd64-3.7\Release\src/minieigen.obj
  minieigen.cpp
  C:\Users\kimeu\AppData\Local\Temp\pip-install-nw28wq3y\minieigen\src\common.hpp(16): fatal error C1083: Cannot open include file: 'Eigen/Core': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for minieigen
  Running setup.py clean for minieigen
Failed to build minieigen
Installing collected packages: minieigen
    Running setup.py install for minieigen ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\kimeu\.virtualenvs\demon_venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kimeu\\AppData\\Local\\Temp\\pip-install-nw28wq3y\\minieigen\\setup.py'"'"'; __file__='"'"'C:\\Users\\kimeu\\AppData\\Local\\Temp\\pip-install-nw28wq3y\\minieigen\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kimeu\AppData\Local\Temp\pip-record-4alqn_2w\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kimeu\.virtualenvs\demon_venv\include\site\python3.7\minieigen'
         cwd: C:\Users\kimeu\AppData\Local\Temp\pip-install-nw28wq3y\minieigen\
    Complete output (13 lines):
    running install
    running build
    running build_ext
    building 'minieigen' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    creating build\temp.win-amd64-3.7\Release\src\double-conversion
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -DEIGEN_DONT_ALIGN -DEIGEN_DONT_VECTORIZE -Isrc -Ic:\src\boost_1_51_0 -Ic:\src\eigen-3.1.1 "-Ic:\program files\python37\include" "-Ic:\program files\python37\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpsrc/minieigen.cpp /Fobuild\temp.win-amd64-3.7\Release\src/minieigen.obj
    minieigen.cpp
    C:\Users\kimeu\AppData\Local\Temp\pip-install-nw28wq3y\minieigen\src\common.hpp(16): fatal error C1083: Cannot open include file: 'Eigen/Core': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\kimeu\.virtualenvs\demon_venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kimeu\\AppData\\Local\\Temp\\pip-install-nw28wq3y\\minieigen\\setup.py'"'"'; __file__='"'"'C:\\Users\\kimeu\\AppData\\Local\\Temp\\pip-install-nw28wq3y\\minieigen\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kimeu\AppData\Local\Temp\pip-record-4alqn_2w\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kimeu\.virtualenvs\demon_venv\include\site\python3.7\minieigen' Check the logs for full command output.
